name = "permit-dashboard"
main = "src/index.ts"
compatibility_date = "2024-03-01"

# D1 database for permit data
[[d1_databases]]
binding = "DB"
database_name = "permit-dashboard"
database_id = "permit-dashboard"

# Workers AI binding
[ai]
binding = "AI"

[vars]
# Add any non-sensitive environment variables here 